defaultSemverRangePrefix: ''

enableGlobalCache: true

nmMode: hardlinks-global

nodeLinker: node-modules

plugins:
  - checksum: 64646be66ec18ce2ecfac7cd71487cd23817d6826b2983c387288c49310260bc4735f815989e9f372bf12ce5a243139de9871fc442a539c5855c771c143bda71
    path: .yarn/plugins/undefined.cjs
    spec: 'https://github.com/WillBooster/yarn-plugin-auto-install/releases/download/v1.8.3/index.cjs'

yarnPath: .yarn/releases/yarn-4.0.0-rc.34.cjs
